# -*- coding: utf-8 -*-
"""Uber_NewYork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQT3CuPYyzsTUn_5nfh7UI9siPqpO3OT
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

os.listdir("/content")

uber_15 =pd.read_csv("/content/uber-raw-data-janjune-15_sample.csv")
uber_15.head()

uber_15.shape

type(uber_15)

uber_15.duplicated().sum()

uber_15.drop_duplicates(inplace=True)

uber_15.duplicated().sum()

uber_15.shape

uber_15.dtypes

uber_15.isnull()

uber_15["Pickup_date"][0]

type(uber_15["Pickup_date"][0])

uber_15["Pickup_date"] = pd.to_datetime(uber_15["Pickup_date"])

type(uber_15["Pickup_date"][0])